services:
  # Backend Service
  - type: web
    name: nasuni-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    
  # Frontend Service
  - type: web
    name: nasuni-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nasuni-backend.onrender.com
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
    autoDeploy: true